function [no_rx, initial_loc, heading, speed, total_time, fs, fc, no_tx, N_SECTORS, orientations, tx_pos] = read_config(config_file)
% Provide a method of inputing configurations quickly
% config file should be of the format generated by gen_config

%   config_file = 'simulation_config.txt';
    a = fopen(config_file, 'r');
    A = fscanf(a, '%c');
    nums = str2double( regexp( A, '-*\d*[\.]*\d*', 'match'));
    no_rx = nums(1);
    nums = nums(2:end);

    for i=1:no_rx
        nums = nums(2:end); % remove header
        initial_loc(i, :) = nums(1:3);
        velocity2 = nums(5:7);
        nums = nums(14:end);
        heading(i) = atan2(velocity2(2), velocity2(1));
        speed(i) = norm(velocity2);
    end

    no_tx = nums(1);
    nums = nums(2:end);

    for i=1:no_tx
        nums = nums(2:end); % remove header
        N_SECTORS = nums(5);
        tx_pos(i, :) = nums(1:3);
        orientations(N_SECTORS*(i-1)+1:i*N_SECTORS, 2) = nums(7:9);
        orientations(N_SECTORS*(i-1)+1:i*N_SECTORS, 1) = nums(11:13);

        nums = nums(22:end);
    end

    fc = nums(1);
    fs = nums(2);
    total_time = nums(3)/fs;


% end

